<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxzxrl7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxzxrl7/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDxzxrl7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDxzxrl7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDxzxrl7\appProdProjectContainer([
    'container.build_hash' => 'Dxzxrl7',
    'container.build_id' => '65f1f8af',
    'container.build_time' => 1644395791,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxzxrl7');
